name: Linter check

on:
  pull_request
  
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:

  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - uses: actions/setup-dotnet@v4
      - name: Dotnet restore
        run: dotnet tool restore
        
      - name: Csharpier format check
        run: |
          dotnet csharpier . --check
          echo "run 'dotnet build' to fix the formatting of the code automatically"
